/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luisb' at '17/11/16 14:33' with Gradle 3.1
 *
 * @author luisb, @date 17/11/16 14:33
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
