/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luisb' at '18/11/16 13:47' with Gradle 3.1
 *
 * @author luisb, @date 18/11/16 13:47
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
